### ISSUE TITLE
Support for shared libraries on Windows

### ISSUE THREAD

**Issue by jwillemsen** [gorlak/premake-ndds#1]
Thanks for the script, it works perfect for static libraries. I am looking at how to extend the script to also compile RTI Connext DDS on Windows using shared libraries. Any suggestions for the best approach? Looks kind has to be "SharedLib" and we need an additional define for each library. Any idea if we can easily do that with some additional configurations?

**Comment by gorlak** [comment]
I wouldn't do it with more configurations, just add an option to turn on shared libs globally, and invoke SharedLib as the module kind: http://industriousone.com/topic/command-line-options-configuration-keywords-premake-dev

**Comment by jwillemsen** [comment]
Looks this is way harder, at the moment we compile shared also the dependencies between all libraries compiled should be correct.

**Comment by gorlak** [comment]
I thought that RTI provided a compiled dll version?

**Comment by jwillemsen** [comment]
Yes, for Visual Studio but not for the MinGw-64 toolchain

**Comment by gorlak** [comment]
Can mingw still not link against import libraries of vstudio-built dlls?  Or is the vc runtime in the way?  I think clang might get you closer than gcc.  Anyway, good luck!
